# CMake generated Testfile for 
# Source directory: C:/Users/jpowe/Desktop/Poietek/native-core
# Build directory: C:/Users/jpowe/Desktop/Poietek-native-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("poietek_native_core_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Debug/poietek_native_core_tests.exe")
  set_tests_properties("poietek_native_core_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;45;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("poietek_native_core_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Release/poietek_native_core_tests.exe")
  set_tests_properties("poietek_native_core_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;45;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("poietek_native_core_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/MinSizeRel/poietek_native_core_tests.exe")
  set_tests_properties("poietek_native_core_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;45;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("poietek_native_core_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/RelWithDebInfo/poietek_native_core_tests.exe")
  set_tests_properties("poietek_native_core_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;45;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
else()
  add_test("poietek_native_core_tests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("poietek_ringbuffer_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Debug/poietek_ringbuffer_tests.exe")
  set_tests_properties("poietek_ringbuffer_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;51;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("poietek_ringbuffer_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Release/poietek_ringbuffer_tests.exe")
  set_tests_properties("poietek_ringbuffer_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;51;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("poietek_ringbuffer_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/MinSizeRel/poietek_ringbuffer_tests.exe")
  set_tests_properties("poietek_ringbuffer_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;51;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("poietek_ringbuffer_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/RelWithDebInfo/poietek_ringbuffer_tests.exe")
  set_tests_properties("poietek_ringbuffer_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;51;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
else()
  add_test("poietek_ringbuffer_tests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("poietek_ring_api_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Debug/poietek_ring_api_tests.exe")
  set_tests_properties("poietek_ring_api_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;57;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("poietek_ring_api_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Release/poietek_ring_api_tests.exe")
  set_tests_properties("poietek_ring_api_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;57;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("poietek_ring_api_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/MinSizeRel/poietek_ring_api_tests.exe")
  set_tests_properties("poietek_ring_api_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;57;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("poietek_ring_api_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/RelWithDebInfo/poietek_ring_api_tests.exe")
  set_tests_properties("poietek_ring_api_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;57;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
else()
  add_test("poietek_ring_api_tests" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("poietek_ring_bulk_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Debug/poietek_ring_bulk_tests.exe")
  set_tests_properties("poietek_ring_bulk_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;62;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("poietek_ring_bulk_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/Release/poietek_ring_bulk_tests.exe")
  set_tests_properties("poietek_ring_bulk_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;62;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("poietek_ring_bulk_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/MinSizeRel/poietek_ring_bulk_tests.exe")
  set_tests_properties("poietek_ring_bulk_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;62;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("poietek_ring_bulk_tests" "C:/Users/jpowe/Desktop/Poietek-native-build/RelWithDebInfo/poietek_ring_bulk_tests.exe")
  set_tests_properties("poietek_ring_bulk_tests" PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;62;add_test;C:/Users/jpowe/Desktop/Poietek/native-core/CMakeLists.txt;0;")
else()
  add_test("poietek_ring_bulk_tests" NOT_AVAILABLE)
endif()
