[package]
name = "poietek-studio"
version = "0.1.0-alpha.0"
description = "Poietek Studio native shell"
authors = ["Poietek"]
edition = "2021"

[lib]
name = "poietek_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
